// <auto-generated />
using System;
using GestionFinanzas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionFinanzas.Data.Migrations
{
    [DbContext(typeof(GestionFinanzasContext))]
    [Migration("20261004234139_AgregarTablaRoles")]
    partial class AgregarTablaRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionFinanzas.Data.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("EstadoActivoCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_activo_categoria");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NombreCategoria")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GestionFinanzas.Data.Meta", b =>
                {
                    b.Property<int>("IdMeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_meta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMeta"));

                    b.Property<bool>("EstadoActivoMeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_activo_meta");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_limite");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("MontoObjetivo")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("monto_objetivo");

                    b.Property<string>("NombreMeta")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_meta");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("saldo_actual");

                    b.HasKey("IdMeta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("GestionFinanzas.Data.Transaccion", b =>
                {
                    b.Property<int>("IdTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_transaccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransaccion"));

                    b.Property<string>("DescripcionTransaccion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion_transaccion");

                    b.Property<bool>("EstadoActivoTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_activo_transaccion");

                    b.Property<DateTime?>("FechaTransaccion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_transaccion");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("monto");

                    b.Property<string>("TipoTransaccion")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_transaccion");

                    b.HasKey("IdTransaccion");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("GestionFinanzas.Data.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ApellidoUsuario")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("apellido_usuario");

                    b.Property<string>("ContraseñaUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contraseña_usuario");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo_usuario");

                    b.Property<bool>("EstadoActivoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_activo_usuario");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("NumeroIdentificacion")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_identificacion");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestionFinanzas.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GestionFinanzas.Models.UsuarioRol", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdRol", "IdUsuario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("GestionFinanzas.Data.Categoria", b =>
                {
                    b.HasOne("GestionFinanzas.Data.Usuario", "IdUsuarioNavigation")
                        .WithMany("Categoria")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_Categorias_Usuarios");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("GestionFinanzas.Data.Meta", b =>
                {
                    b.HasOne("GestionFinanzas.Data.Usuario", "IdUsuarioNavigation")
                        .WithMany("Meta")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Metas_Usuarios");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("GestionFinanzas.Data.Transaccion", b =>
                {
                    b.HasOne("GestionFinanzas.Data.Categoria", "IdCategoriaNavigation")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Transacciones_Categorias");

                    b.HasOne("GestionFinanzas.Data.Usuario", "IdUsuarioNavigation")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Transacciones_Usuarios");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("GestionFinanzas.Models.UsuarioRol", b =>
                {
                    b.HasOne("GestionFinanzas.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFinanzas.Data.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionFinanzas.Data.Categoria", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("GestionFinanzas.Data.Usuario", b =>
                {
                    b.Navigation("Categoria");

                    b.Navigation("Meta");

                    b.Navigation("Transacciones");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("GestionFinanzas.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
